version: '3.4'

services:
  sourcingdb:
    image: mongo

  e-sourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: E-SourcingMicroServices/Dockerfile
